[build-system]
requires = [
    "setuptools",
    "wheel",
    "relenv@git+https://github.com/saltstack/relative-environment-for-python@buildenv",
]
build-backend = "build"
backend-path = ["src/relenv_gdb"]
