name: Pre-Commit

on:
  workflow_call:
    inputs:
      changed-files:
        required: false
        type: string
        description: JSON string containing information about changed files

jobs:
  Pre-Commit:
    name: Pre-Commit Checks

    runs-on: ubuntu-latest

    steps:

      - name: Install System Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y git gcc make zlib1g-dev libc-dev libffi-dev g++ libxml2 libxml2-dev libxslt-dev libcurl4-openssl-dev libssl-dev libgnutls28-dev

      - uses: actions/checkout@v3

      - name: Install Pre-Commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install --install-hooks

      - name: Check ALL Files On Branch
        run: |
          pre-commit run --show-diff-on-failure --color=always --all-files
